# Generated by Django 5.2 on 2026-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creatorupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorupload',
            name='preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='creator_uploads_previews/%Y/%m/%d/'),
        ),
    ]
