# Generated by Django 5.2 on 2025-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_retrotoken_token_alter_retrotoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMiningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('code_A', models.CharField(blank=True, max_length=6, null=True)),
                ('code_B', models.CharField(blank=True, max_length=6, null=True)),
                ('code_C', models.CharField(blank=True, max_length=6, null=True)),
                ('code_D', models.CharField(blank=True, max_length=6, null=True)),
                ('code_E', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
