# Generated by Django 5.2 on 2025-04-27 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userminingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userminingprogress',
            name='code_A',
        ),
        migrations.RemoveField(
            model_name='userminingprogress',
            name='code_B',
        ),
        migrations.RemoveField(
            model_name='userminingprogress',
            name='code_C',
        ),
        migrations.RemoveField(
            model_name='userminingprogress',
            name='code_D',
        ),
        migrations.RemoveField(
            model_name='userminingprogress',
            name='code_E',
        ),
        migrations.AddField(
            model_name='userminingprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userminingprogress',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
