# Generated by Django 5.2 on 2025-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userminingprogress_code_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userminingprogress',
            name='code_A',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userminingprogress',
            name='code_B',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userminingprogress',
            name='code_C',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userminingprogress',
            name='code_D',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userminingprogress',
            name='code_E',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userminingprogress',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
